#spring:
#  application:
#    name: ebankingsystem
#
#  datasource:
#    # url: jdbc:mysql://ebankingsystemdb-1001-ebankingsystemdb.g.aivencloud.com:27032/ebankingsystem?useSSL=true&requireSSL=true&allowPublicKeyRetrieval=true
#    url: jdbc:mysql://localhost:3306/bank
#    # username: ${DB_USERNAME}
#    username: root
#    # password: ${DB_PASSWORD}
#    password: "Pass@123"
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    database-platform: org.hibernate.dialect.MySQLDialect
#    open-in-view: false
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#
#jwt:
#  exp:
#    time: 7200000
#  secret:
#    key: 62d42698ee3ade259800a37310970af1c16a421e5d44f4b0d7831ed714377e4f
#
#logging:
#  level:
#    org.springframework.security: DEBUG
#
#server.error.include-message=always
#server.error.include-binding-errors=always
#server.error.include-stacktrace=always
#logging.level.org.springframework=DEBUG
## jwt.exp.time=7200000
## jwt.secret.key=62d42698ee3ade259800a37310970af1c16a421e5d44f4b0d7831ed714377e4f

spring:
  application:
    name: ebankingsystem

  datasource:
    url: jdbc:mysql://localhost:3306/bank
    username: root
    password: "Pass@123"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update

jwt:
  exp:
    time: 7200000
  secret:
    key: 62d42698ee3ade259800a37310970af1c16a421e5d44f4b0d7831ed714377e4f

server:
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: always

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework: DEBUG

file:
  upload-dir: uploads/kyc