# -----------------------------------------
# Application Name
# -----------------------------------------
spring.application.name=EUREKA-SERVER

# -----------------------------------------
# Eureka Server Port
# -----------------------------------------
server.port=8761

# -----------------------------------------
# Eureka Configuration
# -----------------------------------------

# Eureka Server should not register itself
eureka.client.register-with-eureka=false

# Eureka Server should not fetch registry
eureka.client.fetch-registry=false

# Disable self-preservation during development
eureka.server.enable-self-preservation=false